/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111797-gf225f8d746-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
