name: CMake Multi-Platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          sudo apt-get update && sudo apt-get install libass-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libva-dev libvdpau-dev libvorbis-dev libxcb-xfixes0-dev meson ninja-build pkg-config yasm nasm -y
          git submodule init && git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64
          make
      - name: Package Libraries
        run: |
          mkdir libs
          mv ./FFmpeg/libavcodec/libavcodec.so.60 ./libs/libavcodec.so.60
          mv ./FFmpeg/libavformat/libavformat.so.60 ./libs/libavformat.so.60
          mv ./FFmpeg/libavutil/libavutil.so.58 ./libs/libavutil.so.58
          mv ./FFmpeg/libswresample/libswresample.so.4 ./libs/libswresample.so.4
          mv ./FFmpeg/libswscale/libswscale.so.7 ./libs/libswscale.so.7
          cp -f ./libs/libavcodec.so.60 ./libraries/x64/libavcodec.so
          cp -f ./libs/libavformat.so.60 ./libraries/x64/libavformat.so
          cp -f ./libs/libavutil.so.58 ./libraries/x64/libavutil.so
          cp -f ./libs/libswresample.so.4 ./libraries/x64/libswresample.so
          cp -f ./libs/libswscale.so.7 ./libraries/x64/libswscale.so
      - name: Upload Libraries
        uses: actions/upload-artifact@v4
        with:
          name: lib-linux
          path: libs
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Upload GDExtension
        uses: actions/upload-artifact@v4
        with:
          name: bin-linux
          path: bin/x11
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          brew install yasm automake fdk-aac lame libass libtool libvorbis libvpx opus sdl12-compat shtool texi2html theora x264 x265 xvid nasm
          git submodule init && git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64 --cc='clang -arch x86_64'
          make
      - name: Package Libraries
        run: |
          mkdir libs
          mv ./FFmpeg/libavcodec/libavcodec.60.dylib ./libs/libavcodec.60.dylib
          mv ./FFmpeg/libavformat/libavformat.60.dylib ./libs/libavformat.60.dylib
          mv ./FFmpeg/libavutil/libavutil.58.dylib ./libs/libavutil.58.dylib
          mv ./FFmpeg/libswresample/libswresample.4.dylib ./libs/libswresample.4.dylib
          mv ./FFmpeg/libswscale/libswscale.7.dylib ./libs/libswscale.7.dylib
          cp -f ./libs/libavcodec.60.dylib ./libraries/x64/libavcodec.60.dylib
          cp -f ./libs/libavformat.60.dylib ./libraries/x64/libavformat.60.dylib
          cp -f ./libs/libavutil.58.dylib ./libraries/x64/libavutil.58.dylib
          cp -f ./libs/libswresample.4.dylib ./libraries/x64/libswresample.4.dylib
          cp -f ./libs/libswscale.7.dylib ./libraries/x64/libswscale.7.dylib
      - name: Upload Libraries
        uses: actions/upload-artifact@v4
        with:
          name: lib-macos
          path: libs
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Upload GDExtension
        uses: actions/upload-artifact@v4
        with:
          name: bin-macos
          path: bin/macos
