name: CMake Multi-Platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          sudo apt-get update && sudo apt-get install libass-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libva-dev libvdpau-dev libvorbis-dev libxcb-xfixes0-dev meson ninja-build pkg-config yasm nasm -y
          git submodule init && git submodule update
          rm -r FFmpeg && git clone https://github.com/FFmpeg/FFmpeg
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64
          make
      - name: Package Libraries
        run: |
          mkdir libs
          mv ./FFmpeg/libavcodec/libavcodec.so.61 ./libs/libavcodec.so.61
          mv ./FFmpeg/libavformat/libavformat.so.61 ./libs/libavformat.so.61
          mv ./FFmpeg/libavutil/libavutil.so.59 ./libs/libavutil.so.59
          mv ./FFmpeg/libswresample/libswresample.so.5 ./libs/libswresample.so.5
          mv ./FFmpeg/libswscale/libswscale.so.8 ./libs/libswscale.so.8
          cp -f ./libs/libavcodec.so.61 ./libraries/x64/libavcodec.so
          cp -f ./libs/libavformat.so.61 ./libraries/x64/libavformat.so
          cp -f ./libs/libavutil.so.59 ./libraries/x64/libavutil.so
          cp -f ./libs/libswresample.so.5 ./libraries/x64/libswresample.so
          cp -f ./libs/libswscale.so.8 ./libraries/x64/libswscale.so
      - name: Upload Libraries
        uses: actions/upload-artifact@v4
        with:
          name: lib-linux
          path: libs
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Upload GDExtension
        uses: actions/upload-artifact@v4
        with:
          name: bin-linux
          path: bin/x11
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          brew install yasm automake fdk-aac lame libass libtool libvorbis libvpx opus sdl12-compat shtool texi2html theora x264 x265 xvid nasm
          git submodule init && git submodule update
          rm -r FFmpeg && git clone https://github.com/FFmpeg/FFmpeg
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64 --cc='clang -arch x86_64'
          make
      - name: Package Libraries
        run: |
          mkdir libs
          mv ./FFmpeg/libavcodec/libavcodec.61.dylib ./libs/libavcodec.61.dylib
          mv ./FFmpeg/libavformat/libavformat.61.dylib ./libs/libavformat.61.dylib
          mv ./FFmpeg/libavutil/libavutil.59.dylib ./libs/libavutil.59.dylib
          mv ./FFmpeg/libswresample/libswresample.5.dylib ./libs/libswresample.5.dylib
          mv ./FFmpeg/libswscale/libswscale.8.dylib ./libs/libswscale.8.dylib
          cp -f ./libs/libavcodec.61.dylib ./libraries/x64/libavcodec.61.dylib
          cp -f ./libs/libavformat.61.dylib ./libraries/x64/libavformat.61.dylib
          cp -f ./libs/libavutil.59.dylib ./libraries/x64/libavutil.59.dylib
          cp -f ./libs/libswresample.5.dylib ./libraries/x64/libswresample.5.dylib
          cp -f ./libs/libswscale.8.dylib ./libraries/x64/libswscale.8.dylib
      - name: Upload Libraries
        uses: actions/upload-artifact@v4
        with:
          name: lib-macos
          path: libs
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Upload GDExtension
        uses: actions/upload-artifact@v4
        with:
          name: bin-macos
          path: bin/macos
