name: CMake Multi-Platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          sudo apt-get install mingw-w64
          sudo apt-get update -qq && sudo apt-get -y install autoconf automake build-essential git-core libass-dev libfreetype6-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev meson ninja-build pkg-config texinfo wget yasm zlib1g-dev
          git submodule init
          git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32-
          make
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Package Libraries
        run: |
          cd ./bin/win64
          zip -r bin-windows.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-windows
          path: bin/win64/bin-windows.zip
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          sudo apt-get update -qq && sudo apt-get -y install autoconf automake build-essential git-core libass-dev libfreetype6-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev meson ninja-build pkg-config texinfo wget yasm zlib1g-dev
          git submodule init
          git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64
          make
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Package Libraries
        run: |
          cd ./bin/x11
          zip -r bin-linux.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-linux
          path: bin/x11/bin-linux.zip
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          brew install yasm automake fdk-aac lame libass libtool libvorbis libvpx opus sdl12-compat shtool texi2html theora x264 x265 xvid nasm
          git submodule init
          git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64 --cc='clang -arch x86_64'
          make
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Package Libraries
        run: |
          cd ./bin/macos
          zip -r bin-macos.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-macos
          path: bin/macos/bin-macos.zip
