name: CMake Multi-Platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Submodules
        run: |
          pacman -S make
          pacman -S diffutils
          pacman -S yasm
          pacman -S mingw-w64-x86_64-gcc
          pacman -S pkg-config
          git submodule init
          git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64 --target-os=win64 --toolchain=msvc
          make
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-windows
          path: bin/win64
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          sudo apt-get update -qq && sudo apt-get -y install libass-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libva-dev libvdpau-dev libvorbis-dev libxcb-xfixes0-dev meson ninja-build pkg-config yasm
          git submodule init
          git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64
          make
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-linux
          path: bin/x11
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Submodules
        run: |
          brew install yasm automake fdk-aac lame libass libtool libvorbis libvpx opus sdl12-compat shtool texi2html theora x264 x265 xvid nasm
          git submodule init
          git submodule update
      - name: Configure FFmpeg
        run: |
          cd FFmpeg
          ./configure --enable-pthreads --enable-shared --disable-static --disable-zlib --disable-programs --disable-doc --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe --disable-ffmpeg --arch=x86_64 --cc='clang -arch x86_64'
          make
      - name: Generate Bindings
        run: |
          cd godot-cpp
          cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64
          make
      - name: Build GDExtension
        run: |
          cmake ./CMakeLists.txt
          make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-macos
          path: bin/macos
